name: CI

on:
  workflow_dispatch:

env:
  tf_version: '1.0.3'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.3


      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
     
        run: terraform init -backend-config="token=${{ secrets.TERRAFORM_PROVIDER_TOKEN }}" 

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan 
        continue-on-error: false

      - name: Terraform apply
        id: apply
        run: terraform apply -var "env=dev" -auto-approve 

